feat: add new GitHub Actions for hotfix and release processes with version management
ArkaneNetwork/web3-arkane-provider pull request #96
Opened 2024-08-30 08:52 UTC by koen-venly

…rsion management

2024-09-10 10:21 UTC, nico-ptrs requested changes
I'm not really sure if the actions should be in this project. Shouldn't they be in [venly-github-workflows](https://github.com/ArkaneNetwork/venly-github-workflows)?

2024-09-12 11:12 UTC, koen-venly commented
> I'm not really sure if the actions should be in this project. Shouldn't they be in [venly-github-workflows](https://github.com/ArkaneNetwork/venly-github-workflows)?

Same for all other public projects. We can' use the venly-github-workflows in public projects

2024-10-07 13:53 UTC, nico-ptrs approved these changes

2024-10-08 07:36 UTC, nico-ptrs approved these changes

2024-10-08 07:43 UTC, merged